### PR TITLE
Link unlink

### PR DESCRIPTION
**Pull request by TobiasHauck**
What I don't like is that the local server is responding with 501 instead of 200. Seems that it's not able to handle LINK and UNLINK methods correctly.

### CODE REVIEW

**Comment by ChristopheLecroq** [comment]
Hello Tobias,

I've checked on my side and I received a 200 status code from my Symfony API. I have something like that : 

    return new Response($json, 200, ['content-type' => 'text/json']);

**Comment by TobiasHauck** [comment]
Hey Christophe,

I know it's working. That's why I told you you did well. But our goal is not to publish code that just works, but code that is stable considering a complete testsuite in this case. I'm working on the tests right now ;)

**Comment by ChristopheLecroq** [comment]
My english is limited (but my german is worst... :/). My last post was just a clue to explain why my test returns the 200 code status. 
I'm stopping to bother you and I let you working on this great bundle :)

**Comment by TobiasHauck** [comment]
You don't bother anybody ;) perhaps you can help to find the solution for the problem that we have. We need to test the success and the error case. The error case is not the problem as the local php server returns 501 method not implemented. We need to find a way to test the success case without making external calls...

**Comment by TobiasHauck** [comment]
Have a look at #24 
We are not able to test LINK/UNLINK properly as they are deprecated, but we have changed the bundle to extend it by your own.

**Pull request closed without merging**
